### ISSUE TITLE
Crashing when images are used in combination with multiple pages

### ISSUE THREAD

**Issue by dadiggi** [gickowtf/pixoo-homeassistant#12]
Hi,
I have noticed this issue when using custom images on a text page. Pixoo will not crash/reboot if there is only one page with combo of images and texts in yaml, however, if I add any additional page, ie. some clock or channel on the 2nd page, it will crash after looping back to the 1st page.
If there's only text on the page, without any image, it will loop normally through pages.
Example:
`ip_address: 'xxx.xxx.xxx.xxx'
scan_interval:
  seconds: 15
pages:
  - page: 1
    texts:
      - text: "{{ states.sensor.tado_heating_temperature.state | round(1) }} C"
        position: [20, 7]
        font: FONT_PICO_8
        font_color: [50, 205, 50] 
      - text: "{{ states.sensor.tado_heating_helper_outdoor_temperature.state | round(1) }} C"
        position: [20, 25]
        font: FONT_PICO_8
        font_color: [50, 205, 50] 
      - text: "{{ states.sensor.tado_heating_humidity.state | round(1) }} %"
        position: [20, 43]
        font: FONT_PICO_8
        font_color: [50, 205, 50] 
    images:
      - image: "/config/custom_components/divoom_pixoo/img/inside_temperature.png" #max 64 x 64 Pixel
        position: [1, 1]
      - image: "/config/custom_components/divoom_pixoo/img/outside_temperature.png" #max 64 x 64 Pixel
        position: [1, 18]
      - image: "/config/custom_components/divoom_pixoo/img/inside_humidity.png" #max 64 x 64 Pixel
        position: [1, 35]
  - page: 2
    channel:
      - number: 1`

This will crash, but if I remove or comment out images section, or have only 1st page, it'll work normally.

**EDIT: adding a log from HA**

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/divoom_pixoo/pixoo64/_pixoo.py:386
Integration: Divoom Pixoo 64 (documentation, issues)
First occurred: 23:36:12 (9 occurrences)
Last logged: 23:39:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.12/http/client.py", line 1327, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1373, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1322, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1081, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1025, in send
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3cc40f66f0>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.50.225', port=80): Max retries exceeded with url: /post (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cc40f66f0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/divoom_pixoo/sensor.py", line 108, in _async_update
    await self._async_update_data()
  File "/config/custom_components/divoom_pixoo/sensor.py", line 169, in _async_update_data
    await self.hass.async_add_executor_job(update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/divoom_pixoo/sensor.py", line 134, in update
    pixoo = Pixoo(self._ip_address)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/divoom_pixoo/pixoo64/_pixoo.py", line 86, in __init__
    self.__load_counter()
  File "/config/custom_components/divoom_pixoo/pixoo64/_pixoo.py", line 386, in __load_counter
    response = requests.post(self.__url, '{"Command": "Draw/GetHttpGifId"}')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.50.225', port=80): Max retries exceeded with url: /post (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cc40f66f0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
`

**UPDATE 1**: I've found out some kind of a workaround for this - as long as there's some lighter page (text only) put between heavier (ie. clock, channel...) and a custom page (with text and images), it will not crash.

**Comment by Mrredstone5230** [comment]
I do have to agree with you. I only used the default config without the PV page and my pixoo reaaaally doesn't like it. I think I found a fix for it, as in the code, it would send a request to show the custom page twice per page if there was text and images on the same page.
